language: java
jdk:
  - openjdk8
branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x ./gradlew

script:
  - ./gradlew clean build

before_deploy:
  - mkdir -p deploy
  - mv build/lis/*.jar deploy

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "bgpark-s3"
  skip_cleanup: true
  region: ap-northeast-2

notifications:
  slack: letshadow:xdR2SxYrzBCWVZODKrsTbwZB